### ISSUE TITLE
Improvement - Add Automatic Dashboard and Plot Resizing

### ISSUE THREAD

**Issue by xFiveRivers** [UBC-MDS/climadash#31]

**Comment by Lorraine97** [comment]
https://shiny.rstudio.com/reference/shiny/0.11/fixedpage
https://shiny.rstudio.com/reference/shiny/0.13.1/fillpage

After some research, I found that these two will meet the requirements, however, we will sacrifice the benefits of the sidebar. Therefore, I will proceed to improve the visualization by refactoring it into a dashboard instead.
